#spring:
# datasource:
#  url: jdbc:mysql://localhost:3306/users
#  username: root
#  password: root
# jpa:
#  hibernate:
#   ddl-auto: update
#  show-sql: true
spring:
  database: h2
  console: 
    enabled: true
    path: /h2

datasource:
  platform: h2
  url: jdbc:h2:mem:RegistrationDb
  username: sa
  password: 1234
  driverClassName: org.h2.Driver
server:
 port: 8081

